# Generated by Django 6.0.4 on 2026-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('dtNasc', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('renda', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Renda')),
            ],
        ),
    ]
